# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "27bee79bfa6071d88605e515871d4a7d"
name = "AI Instafeed"
application_url = "https://orlando-questions-roads-sagem.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_themes"

[auth]
redirect_urls = [
  "https://orlando-questions-roads-sagem.trycloudflare.com/api/auth/callback",
  "http://localhost:3000/api/auth/callback"
]

[app_proxy]
url = "https://orlando-questions-roads-sagem.trycloudflare.com/api"
subpath = "instafeed"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
